;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	coffee-dedent-line-backspace
	kill-region
	kill-sexp
	org-shiftleft
	paredit-backward
	paredit-backward-kill-word
	paredit-backward-slurp-sexp
	paredit-backward-up
	paredit-close-round
	paredit-doublequote
	paredit-forward
	paredit-forward-barf-sexp
	paredit-forward-down
	paredit-forward-slurp-sexp
	paredit-kill
	paredit-open-round
	paredit-semicolon
	paredit-splice-sexp
	paredit-splice-sexp-killing-backward
	transpose-sexps
	transpose-words
	))

(setq mc/cmds-to-run-once
      '(
	helm-M-x
	))
